export { default as authService } from './auth'
export { default as dashboardService } from './dashboard'
export { default as documentsService } from './documents'
export { default as aiService } from './ai'
export { default as flashcardsService } from './flashcards'
export { default as quizService } from './quiz'
