export { default as Login } from './auth/login'
export { default as Register } from './auth/register'
export { default as Dashboard } from './dashboard'
export { default as Document } from './document'
export { default as Error } from './error'
export { default as NotFound } from './not-found'
export { default as DocumentDetails } from './document/document-details'
